IngramWorkFlow/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using IngramWorkFlow.Business.DataAccess;
using IngramWorkFlow.Business.Model;
using IngramWorkFlow.Models;

namespace IngramWorkFlow.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ISettingsProvider _settingsProvider;

        public SettingsController(ISettingsProvider settingsProvider)
        {
            _settingsProvider = settingsProvider;
        }

        public ActionResult Edit()
        {
            return View(GetModel());
        }

        #region Other
        private SettingsModel GetModel()
        {
            var model = new SettingsModel
            {
                SchemeName = "SimpleWF"
            };

            var config = _settingsProvider.GetSettings();
            model.Users = config.Users;
            model.Roles = config.Roles;
            model.StructDivision = config.StructDivision;

            return model;
        }

        public static string GenerateColumnHtml(string name, StructDivision m, List<StructDivision> Model, List<User> users, ref int index, string refId)
        {
            string valuePrefix = string.Format("{0}[{1}]", name, index);

            var sb = new StringBuilder();
            string trName = string.Format("tr_{0}{1}", name, index);

            sb.AppendFormat("<tr Id='{0}' {1}>", trName,
                            string.IsNullOrEmpty(refId) ? string.Empty : string.Format("class='child-of-{0}'", refId));
            sb.AppendFormat("<input type='hidden' name='{0}.Id' value='{1}'></input>", valuePrefix, m.Id);
            sb.AppendFormat("<input type='hidden' name='{0}.ParentId' value='{1}'></input>", valuePrefix, m.ParentId);
            sb.AppendFormat("<td class='columnTree'><b>{0}</b></td>", m.Name);
            sb.AppendFormat("<td></td>");
            sb.Append("</tr>");

            foreach (var item in users.Where(c => c.StructDivisionId == m.Id))
            {
                index++;
                sb.Append(GenerateColumnHtml(name, item, ref index, trName));
            }

            foreach (var item in Model.Where(c => c.ParentId == m.Id))
            {
                index++;
                sb.Append(GenerateColumnHtml(name, item, Model, users, ref index, trName));
            }

            return sb.ToString();
        }

        public static string GenerateColumnHtml(string name, User m, ref int index, string refId)
        {
            string valuePrefix = string.Format("{0}[{1}]", name, index);

            var sb = new StringBuilder();
            string trName = string.Format("tr_{0}{1}", name, index);

            sb.AppendFormat("<tr Id='{0}' {1}>", trName,
                            string.IsNullOrEmpty(refId) ? string.Empty : string.Format("class='child-of-{0}'", refId));
            sb.AppendFormat("<input type='hidden' name='{0}.Id' value='{1}'></input>", valuePrefix, m.Id);
            sb.AppendFormat("<td class='columnTree'>");
            sb.AppendFormat("{0}", m.Name);
            sb.AppendFormat("</td>");
            sb.AppendFormat("<td>");
            sb.AppendFormat("{0}", string.Join(",", m.UserRoles.Select(c => c.Role.Name).ToArray()));
            sb.AppendFormat("</td>");
            sb.Append("</tr>");

            return sb.ToString();
        }
        #endregion
    }
}

IngramWorkFlow/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using IngramWorkFlow.Business.Model;
using IngramWorkFlow.Business.Workflow;
using IngramWorkFlow.Helpers;
using IngramWorkFlow.Models;
using System.Threading;
using AutoMapper;
using IngramWorkFlow.Business.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace IngramWorkFlow.Controllers
{
  
    public class TicketController : Controller
    {
        private readonly ITicketRepository _ticketRepository;
        private readonly IUserRepository _userRepository;
        private readonly IMapper _mapper;

        public TicketController(ITicketRepository ticketRepository, IUserRepository userRepository, IMapper mapper)
        {
            _ticketRepository = ticketRepository;
            _userRepository = userRepository;
            _mapper = mapper;
        }

        #region Index
        public ActionResult Index(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            return View(new TicketListModel()
            {
                Page = page,
                PageSize = pageSize,
                Docs = _ticketRepository.Get(out count, page, pageSize).Select(c=> GetDocumentModel(c)).ToList(),
                Count = count,
            });
        }

        public ActionResult Inbox(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            return View("Index", new TicketListModel()
            {
                Page = page,
                PageSize = pageSize,
                Docs = _ticketRepository.GetInbox(CurrentUserSettings.GetCurrentUser(HttpContext), out count, page, pageSize)
                        .Select(c => GetDocumentModel(c)).ToList(),
                Count = count,
            });
        }

        public ActionResult Outbox(int page = 0)
        {
            int count = 0;
            const int pageSize = 15;

            return View("Index", new TicketListModel()
            {
                Page = page,
                PageSize = pageSize,
                Docs = _ticketRepository.GetOutbox(CurrentUserSettings.GetCurrentUser(HttpContext), out count, page, pageSize)
                        .Select(c => GetDocumentModel(c)).ToList(),
                Count = count,
            });
        }
        #endregion

        #region Edit
 
       
        public ActionResult Edit(Guid? Id)
        {
            TicketModel model = null;

            if(Id.HasValue)
            {
                var d = _ticketRepository.Get(Id.Value);
                if(d != null)
                {
                    CreateWorkflowIfNotExists(Id.Value,"ITADPickup");

                    var h = _ticketRepository.GetHistory(Id.Value);
                    model = new TicketModel()
                                {
                                    Id = d.Id,
                                    AuthorId = d.AuthorId,
                                    AuthorName = d.Author.Name,
                                    Comment = d.Comment,
                                    ManagerId = d.ManagerId,
                                    ManagerName =
                                        d.ManagerId.HasValue ? d.Manager.Name : string.Empty,
                                    Name = d.Name,
                                    Number = d.Number,
                                    StateName = d.StateName,
                                    Commands = GetCommands(Id.Value),
                                    AvailiableStates = GetStates(Id.Value),
                                    HistoryModel = new TicketHistoryModel{Items = h}
                                };
                }
                
            }
            else
            {
                Guid userId = CurrentUserSettings.GetCurrentUser(HttpContext);
                model = new TicketModel()
                        {
                            AuthorId = userId,
                            AuthorName = _userRepository.GetNameById(userId),
                            StateName = "Request created"
                        };
            }

            return View(model);
        }

        [HttpPost]
        [Route("createFlow")]
        public IActionResult postEdit([FromQuery]string schemeCode, [FromBody] TicketModel model)
        {
           // return Edit(null);
            return Edit(null, null, model, schemeCode,"");
        }
        [HttpPost]
        [Route("Command")]
        public IActionResult postCommand([FromQuery]string commandName,[FromQuery] string userid,[FromBody] TicketModel  model)
        {

            var commands = WorkflowInit.Runtime.GetAvailableCommands(model.Id, userid);

            var command =
                commands.FirstOrDefault(
                    c => c.CommandName.Equals(commandName, StringComparison.CurrentCultureIgnoreCase));
            if (command == null)
                return null;
            return Edit(model.Id, commandName,model, "", userid);
        }
        [HttpPost]
        public ActionResult Edit(Guid? Id,string button,TicketModel model, string schemeCode, string currentUser)
        {
         
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            string json = JsonConvert.SerializeObject(model);
            Ticket doc = _mapper.Map<Ticket>(model);

            try
            {
                doc = _ticketRepository.InsertOrUpdate(doc);
                if(button == null)
                   WorkflowInit.Runtime.CreateInstance(schemeCode,doc.Id);
                if (doc == null)
                {
                    ModelState.AddModelError("", "Row not found!");
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                var sb = new StringBuilder("Error " + ex.Message);
                if (ex.InnerException != null)
                    sb.AppendLine(ex.InnerException.Message);
                ModelState.AddModelError("", sb.ToString());
                return View(model);
            }
            if(button == null)
            {
                return Ok(doc.Id);
            }

            if (button == "SaveAndExit")
                return RedirectToAction("Inbox");
            
            if (button != "Save")
            {
                ExecuteCommand(doc.Id, button, model,currentUser);
            }
            return RedirectToAction("Edit", new { doc.Id });

        }
        #endregion

        #region Delete
        public ActionResult DeleteRows(Guid[] ids)
        {
            if (ids == null || ids.Length == 0)
                return Content("Items not selected");

            try
            {
                _ticketRepository.Delete(ids);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

            return Content("Rows deleted");
        }
        #endregion

        #region Workflow
        private TicketCommandModel[] GetCommands(Guid id)
        {
            var result = new List<TicketCommandModel>();
            var commands = WorkflowInit.Runtime.GetAvailableCommands(id, CurrentUserSettings.GetCurrentUser(HttpContext).ToString());
            foreach (var workflowCommand in commands)
            {
                if (result.Count(c => c.key == workflowCommand.CommandName) == 0)
                    result.Add(new TicketCommandModel() { key = workflowCommand.CommandName, value = workflowCommand.LocalizedName, Classifier = workflowCommand.Classifier });
            }
            return result.ToArray();
        }

        private Dictionary<string, string> GetStates(Guid id)
        {

            var result = new Dictionary<string, string>();
            var states = WorkflowInit.Runtime.GetAvailableStateToSet(id);
            foreach (var state in states)
            {
                if (!result.ContainsKey(state.Name))
                    result.Add(state.Name, state.VisibleName);
            }
            return result;

        }

        private void ExecuteCommand(Guid id, string commandName, TicketModel document, string currentUser)
        {
          //  var currentUser = CurrentUserSettings.GetCurrentUser(HttpContext).ToString();
            
            if (commandName.Equals("SetState", StringComparison.InvariantCultureIgnoreCase))
            {
                if (string.IsNullOrEmpty(document.StateNameToSet))
                    return;

                WorkflowInit.Runtime.SetState(id, currentUser, currentUser, document.StateNameToSet, new Dictionary<string, object> { { "Comment", document.Comment } });
                return;
            }

            var commands = WorkflowInit.Runtime.GetAvailableCommands(id, currentUser);

            var command =
                commands.FirstOrDefault(
                    c => c.CommandName.Equals(commandName, StringComparison.CurrentCultureIgnoreCase));
            
            if (command == null)
                return;

            if (command.Parameters.Count(p => p.ParameterName == "Comment") == 1)
                command.Parameters.Single(p => p.ParameterName == "Comment").Value = document.Comment ?? string.Empty;

            WorkflowInit.Runtime.ExecuteCommand(command,currentUser,currentUser);
        }

        private void CreateWorkflowIfNotExists(Guid id,string schemeCode)
        {
            if (WorkflowInit.Runtime.IsProcessExists(id))
                return;

            WorkflowInit.Runtime.CreateInstance(schemeCode, id);
        }

        #endregion

        public ActionResult RecalcInbox()
        {
            var newThread = new Thread(WorkflowInit.RecalcInbox);
            newThread.Start();
            return Content("Calculating inbox started!");
        }

        private TicketModel GetDocumentModel(Ticket d)
        {
            return new TicketModel()
            {

IngramWorkFlow/Views/Shared/Partial/Folders.cshtml
@using System.Linq
@using Microsoft.AspNetCore.Http.Extensions

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor ContextAccessor

@{
    int folder = 0;
    if (ContextAccessor.HttpContext != null)
    {
        if (ContextAccessor.HttpContext.Request.GetEncodedUrl().ToLower().Contains("inbox"))
        {
            folder = 1;
        }
        else if (ContextAccessor.HttpContext.Request.GetEncodedUrl().ToLower().Contains("outbox"))
        {
            folder = 2;
        }
    }
}

@*<div style="width: 300px; float: left;">
    <div class="ui menu">
        <a href="/" class="item">@Html.Raw(folder == 0 ? "<b>Tickets</b>" : "All Requests")</a>
        <a href="/Ticket/Inbox" class="item">@Html.Raw(folder == 1 ? "<b>Inbox</b>" : "Inbox")</a>
        <a href="/Ticket/Outbox" class="item">@Html.Raw(folder == 2 ? "<b>Outbox</b>" : "Outbox")</a>
    </div>
</div>*@

<script>
    function ReCalcInbox() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("RecalcInbox", "Ticket")",
            success: function (msg) {
                alert(msg);
            }
        });
    }

</script>

IngramWorkFlow/Views/Shared/Partial/Footer.cshtml
<div class="wfe-application-footer">
    <span style="padding-top: 20px;">
    </span>
</div>

IngramWorkFlow/Views/Shared/Partial/Header.cshtml
@*@using System.Linq
@using IngramWorkFlow.Business.Model
@using IngramWorkFlow.Helpers
@using IngramWorkFlow.Business.DataAccess

@inject IEmployeeRepository EmployeeRepository
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor ContextAccessor

@{
    Guid currentEmployeeId = CurrentUserSettings.GetCurrentUser(ContextAccessor.HttpContext);

    if (currentEmployeeId == Guid.Empty)
    {
        IList<Employee> list = EmployeeRepository.GetAll();
        if (list != null && list.Count > 0)
        {
            currentEmployeeId = list[0].Id;
            CurrentUserSettings.SetUserInCookies(ContextAccessor.HttpContext, currentEmployeeId);
        }
    }

    var htmlAtt = new Dictionary<string, object>();
    htmlAtt.Add("class", "ui dropdown");
    htmlAtt.Add("onchange", "CurrentEmployee_OnChange(this);");


}
<script>
    function CurrentEmployee_OnChange(sender) {
        window.location.search = "CurrentEmployee=" + sender.value;
    }
</script>

<div class="ui form" style="min-width: 300px; float: right;">
    <div class="field">
        <label>Current employee</label>
        @Html.DropDownList("CurrentEmployee",
                         EmployeeRepository.GetAll().Select(item => new SelectListItem()
                         {
                             Text = string.Format("Name: {0}; StructDivision: {1}; Roles: {2}", item.Name, item.StructDivision.Name, item.GetListRoles()),
                             Value = item.Id.ToString(),
                             Selected = item.Id == currentEmployeeId
                         }).ToList(),
                        htmlAtt)
    </div>
</div>*@

IngramWorkFlow/Views/Shared/Partial/MainMenu.cshtml
<div class="wfe-application-mainmenu">
    @*<div style="float:left">
        <div class="logotitle">
         <img height="32" src="@Url.Content("~/images/logo.jpg")" /></div>
    </div>
    <div style="float:right">
        @*<a href="/Document/Edit" class="ui primary button">Execute</a>*@
        @*<a href="/Designer" class="ui secondary button">Designer</a>*@
        @*<a href="/" class="ui secondary button">Requests</a>
        <a href="@Url.Action("Edit", "Settings")" class="ui secondary button">Settings</a>
    </div>*@
</div>